### PR TITLE
fix(react-grid): Fixed column cell of selected row is not highlighted

### LINKED ISSUE #1948: DataGrid - Fixed column cell of selected row is not highlighted
### Steps to Reproduce:

1. Take a simple Grid
2. Add TableSelection
3. Add TableFixedColumns
4. Add columns to TableFixedColumns

Example here: https://codesandbox.io/s/l51v63mj5m

### Results You Received:
All cells from selected row are highlighted, apart from the cell from the fixed column

### Results You Expected:
All cells from selected row to be highlighted

### PR DESCRIPTION
**Pull request by churkin**
close #1948

### CODE REVIEW

File: packages/dx-react-grid-bootstrap4/src/templates/table-select-row.jsx [hunk 1]
```diff
@@ -1,16 +1,20 @@
...
   children,
   style,
   onToggle,
   selectByRowClick,
+  className,
 }) => (
   <tr
     style={style}
-    className={selected ? 'table-active' : ''}
+    className={classNames({
```
Comment (ushkal) [inline packages/dx-react-grid-bootstrap4/src/templates/table-select-row.jsx]: We should test that custom className is applied in such places
