### PR TITLE
fix(react-grid): rework controlled mode

### LINKED ISSUE #762: Cursor jumps to the end after changing an editor value in controlled mode
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

When editing a column/textfield - say I insert a character in the middle of the existing word (like Paris on your docs page in the controlled example: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/) - after insertion, the cursor jumps to the end of the textbox.

### Expected Behaviour

The cursor should not jump to the end of the textbox, as it won't allow me to add two characters without having to reset the insertion point.

### Steps to Reproduce (for Bugs)

Go to your docs to the controlled example - and change "Paris" to "Pahris"
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/

### Your Environment

devextreme-reactive: 1.0.1
react: xxx
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0.beta33

### PR DESCRIPTION
**Pull request by kvet**
fixes #762

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/integrated-selection/computeds.js [hunk 1]
```diff
@@ -1,22 +1,24 @@
-export const getAvailableToSelect = (rows, getRowId, isGroupRow) => {
+export const rowsWithAlailableToSelect = (rows, getRowId, isGroupRow) => {
```
Comment (gsobolev) [inline packages/dx-grid-core/src/plugins/integrated-selection/computeds.js]: `rowsWithAlailableToSelect` -> `rowsWithAvailableToSelect`

File: packages/dx-react-grid/src/plugins/integrated-selection.jsx [hunk 2]
```diff
@@ -1,52 +1,43 @@
 import React from 'react';
 import { Getter, Action, Plugin } from '@devexpress/dx-react-core';
 import {
-  getAvailableToSelect,
+  rowsWithAlailableToSelect,
   someSelected,
   allSelected,
+  unwrapSelecetedRows,
```
Comment (gsobolev) [inline packages/dx-react-grid/src/plugins/integrated-selection.jsx]: `unwrapSelecetedRows` -> `unwrapSelectedRows`
