### PR TITLE
fix(react-grid): correct displaying "No data" message in Edge

### LINKED ISSUE #2330: "No data" message is incorrectly displayed in Edge
When we use Fixed Columns and have no rows to display, the "No data" message is displayed in the wrong place.

image

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2330

### CODE REVIEW

File: packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx [hunk 1]
```diff
@@ -1,20 +1,7 @@
 import * as React from 'react';
 import * as PropTypes from 'prop-types';
-import { getStickyPosition } from '../utils/css-fallback-properties';
 
 export class TableNoDataCell extends React.PureComponent {
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: Should we keep the `class` here if we don't use the `constructor`?

File: packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx [hunk 2]
```diff
@@ -38,7 +24,7 @@ export class TableNoDataCell extends React.PureComponent {
         <div
           style={{
             display: 'inline-block',
-            position: stickyPosition,
+            position: 'fixed',
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: We can extract it into constant

Comment (LazyLahtak) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: What does you mean? It is normal CSS value.

Comment (MaximKudriavtsev) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]:
```js
const style = {
  display: 'inline-block',
  position: 'fixed',
  // and so on...
};

// ...

<div
  style={style}
>
```

Comment (LazyLahtak) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: Should we do that? We use that style once, in this `div`

Comment (MaximKudriavtsev) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: We create a new object on each render. We often try to avoid similar cases.

File: packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx [hunk 3]
```diff
@@ -1,62 +1,42 @@
...
+      padding: '50px 0',
+      ...style,
+    }}
+    colSpan={colSpan}
+    {...restProps}
+  >
+    <div
+      style={{
+        display: 'inline-block',
+        position: 'fixed',
```
Comment (ushkal) [inline packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: 'fixed' position is a bad idea because it's relative to a page not a grid

Comment (LazyLahtak) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: When "No data" message is relative to grid, we get wrong result (see GIF). If we should'n make some relate to page, we need to relate on grid's container.
Also is message relative to page critical? I tried to resize, zoom and move window and didn't break this.
GIF123123123123123123123

Comment (ushkal) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: Well, try to set grid's width to 300px and a page height to 3000px

Comment (LazyLahtak) [reply packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx]: I get it, I'll try another.

**Comment by LazyLahtak** [comment]
FPR

**Comment by LazyLahtak** [comment]
FPR
