### PR TITLE
fix(react-grid): avoid rendering group summary row if no footer summary exists

### LINKED ISSUE #2741: An empty group summary row is rendered if no total group summaries are specified
image

https://github.com/DevExpress/devextreme-reactive/issues/2722#event-3114189574

Hello, I bought it using 2.5.1v. But the second problem I mentioned continues. When you print the total up, the blank line remains below.

### PR DESCRIPTION
**Pull request by ushkal**
fixes #2741

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/table-summary-row/helpers.ts [hunk 1]
```diff
@@ -44,6 +44,8 @@ export const isInlineGroupCaptionSummary: PureComputed<[SummaryItem], boolean> =
   !((summaryItem as GroupSummaryItem).showInGroupFooter ||
   (summaryItem as GroupSummaryItem).alignByColumn)
 );
+export const groupFooterSummaryExists: PureComputed<[GroupSummaryItem[]], boolean> =
+  groupSummaryItems => groupSummaryItems?.filter(isFooterSummary).length > 0;
```
Comment (LazyLahtak) [inline packages/dx-grid-core/src/plugins/table-summary-row/helpers.ts]: This could be more effectively when we have many groups.
```js
groupSummaryItems?.some(isFooterSummary)
```
