### PR TITLE
fix(core): fix third element update

### LINKED ISSUE #3036: When the Toolbar has more than 2 elements, conditionally showing GroupingPanel does not work
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When the Toolbar has more than 2 elements, conditionally showing `GroupingPanel` does not work.

### Expected Behaviour
Showing/hiding GroupingPanel based on a property should work regardless of how many items there are in the Toolbar.

### Steps to Reproduce

Create a Toolbar with 3 items, one being a GroupingPanel, and add a condition to show/hide the GroupingPanel:

```
<Toolbar />
{grouping && <GroupingPanel />}
<SearchPanel />
<ColumnChooser />
```

Link to the example that reproduces the issue: [Example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-co4ne?file=/index.js)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: Chrome 84.0.4147.125
- material-ui: 4.11.0

### PR DESCRIPTION
**Pull request by Krijovnick**
Fixes #3036

### CODE REVIEW

File: packages/dx-react-core/src/plugin-based/template-placeholder.tsx [hunk 1]
```diff
@@ -65,8 +65,9 @@ class TemplatePlaceholderBase extends React.Component<Props> {
   shouldComponentUpdate(nextProps: Props) {
     const { params, templates } = getRenderingData(nextProps);
     const { children } = this.props;
-    const [template] = templates;
-    return children !== nextProps.children || this.template !== template
+
+    return children !== nextProps.children || templates.length > 1
```
Comment (MikeVitik) [inline packages/dx-react-core/src/plugin-based/template-placeholder.tsx:69]: shallowEqual(this.templates, templates)

Comment (MikeVitik) [inline packages/dx-react-core/src/plugin-based/template-placeholder.tsx:69]: Try to use the following code instead:
````
const [template] = templates;
return children !== nextProps.children || templates.length > 1
      || this.template !== template
      || !shallowEqual(this.params, params);
````

**Review by MikeVitik — APPROVED** [review]
