### PR TITLE
fix(react-grid): calculate visible rows when rendering VirtualTable

### LINKED ISSUE #748: VirtualTable should update when height changes
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Changing the height of VirtualTable doesn't update its contents.
Rows hidden because of a small height stay hidden when the height is increased.
After increasing the height scrolling is necessary to update the view.

### Expected Behaviour

Scrolling should not be necessary. Changing the height should suffice.

### Steps to Reproduce (for Bugs)

https://codesandbox.io/s/1yor2kwvkq

### Your Environment

devextreme-reactive: 1.0.0
react: 16.2.0
browser: Chrome 64.0.3282.167
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.31

### PR DESCRIPTION
**Pull request by kvet**
fixes #748

### CODE REVIEW

File: packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx [hunk 1]
```diff
@@ -104,9 +102,8 @@ export class VirtualTableLayout extends React.PureComponent {
     }
 
     if (this.viewportTop !== node.scrollTop) {
-      this.viewportTop = node.scrollTop;
       this.setState({
-        visibleBodyRows: this.getVisibleRows(),
+        viewportTop: node.scrollTop,
```
Comment (SergeyAlexeev) [inline packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx]: Can we extract `scrollTop` from `node`? It's using a lot of times.

Comment (kvet) [reply packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx]: Yes, we can, but I am not sure that we should. Seems like function will become more verbose.
