### PR TITLE
fix(react-grid): rerender only cell being edited in inline cell editing mode

### LINKED ISSUE #2499: TableInlineCellEditing rerenders all cells during editing
## Current Behaviour

All table cells are rerendered after a user types any character in TableInlineCellEditing's editor.

## Expected Behaviour

Only the cell that is being edited should be rerendered.

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2499

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import { TableRowWithEditingCellsFn, TableColumnsWithEditingCellsFn } from '../../types';
+
+export const rowsWithEditingCells: TableRowWithEditingCellsFn = (
```
Comment (ushkal) [inline packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.ts]: -> TableRowsWithEditingCellsFn

File: packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx [hunk 2]
```diff
@@ -18,115 +21,131 @@ const pluginDependencies = [
...
+          <TemplateConnector>
+            {({}, { startEditCells }) => {
+              const { tableRow, tableColumn } = params;
+              const { rowId } = tableRow;
+              const { column } = tableColumn;
+              const { name: columnName } = column!;
+
+              if (startEditAction !== 'click' && startEditAction !== 'doubleClick') {
+                throw new Error(INLINE_CELL_EDITING_ERROR);
+              }
```
Comment (ushkal) [inline packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx]: We only need an event name, so better write
```const eventName = ...
newParams = { ... [eventName]: startEditCellCallback }
```

File: packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx [hunk 3]
```diff
@@ -18,115 +21,131 @@ const pluginDependencies = [
...
-          tableRow.type === TABLE_DATA_TYPE && tableColumn.type === TABLE_DATA_TYPE
+        predicate={({ tableRow, tableColumn }: any) =>
+          tableRow.type === TABLE_DATA_TYPE &&
+          tableColumn.type === TABLE_DATA_TYPE
+        }
+      >
+        {(params: TableCellProps) => (
+          <TemplateConnector>
+            {({}, { startEditCells }) => {
+              const { tableRow, tableColumn } = params;
```
Comment (ushkal) [inline packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx]: it can be destructured in 1 call: `const { tableRow : { rowId, row }, tableColumn: { column } } = params;`
