### PR TITLE
fix(react-grid): pass style field to editCellTemplate of TableEditRow

### LINKED ISSUE #234: Problem w/ editing when using VirtualTableView
When i click edit on a row  when using VirtualTableView the edit column seems to lose its width and all other columns are pushed to the left of the table, my component construction seems to work fine when using regular TableView though.

### PR DESCRIPTION
**Pull request by kvet**
Fixes #234

### CODE REVIEW

File: packages/dx-react-grid/src/plugins/table-edit-row.jsx [hunk 1]
```diff
@@ -40,11 +40,12 @@ export class TableEditRow extends React.PureComponent {
             changeRow: ({ rowId, change }) => action('changeRow')({ rowId, change }),
           })}
         >
-          {({ rowId, row, column, value, changeRow }) =>
+          {({ rowId, row, column, value, changeRow, style }) =>
             editCellTemplate({
               row,
               column,
               value,
+              style,
```
Comment (kvet) [inline packages/dx-react-grid/src/plugins/table-edit-row.jsx]: Tests for this is prepared in #227

File: packages/dx-react-grid/src/plugins/table-edit-row.jsx [hunk 2]
```diff
@@ -68,11 +69,12 @@ export class TableEditRow extends React.PureComponent {
             changeAddedRow: ({ rowId, change }) => action('changeAddedRow')({ rowId, change }),
           })}
         >
-          {({ row, rowId, column, value, changeAddedRow }) =>
+          {({ row, rowId, column, value, changeAddedRow, style }) =>
```
Comment (kvet) [inline packages/dx-react-grid/src/plugins/table-edit-row.jsx]: The same here
