### PR TITLE
fix(react-grid): allow columns bands to work in virtual table

### LINKED ISSUE #1389: Banded columns and virtual table bug
I use VirtualTable and BandedColumns together, column header cells behave strangely when horizontal scrolling. I think colspan is calculated incorrectly for banded columns. When the first column from group is removed from DOM, its banded header cell it is also removed

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### PR DESCRIPTION
**Pull request by ushkal**
fixes #1389

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/table-band-header/computeds.ts [hunk 1]
```diff
@@ -73,3 +75,67 @@ export const tableHeaderColumnChainsWithBands: GetHeaderColumnChainsFn<
...
+const getBandLevel: PureComputed<[any[], string, number?], number> = (
+  bands, bandTitle, level = 0,
+) => {
+  for (const band of bands) {
+    if (band.title === bandTitle) {
+      return level;
+    }
+    if (band.children !== undefined) {
+      const result = getBandLevel(band.children, bandTitle, level + 1);
+      if (result >= 0) return result;
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-band-header/computeds.ts]: We can include `result >= 0` into above `if`

Comment (ushkal) [reply packages/dx-grid-core/src/plugins/table-band-header/computeds.ts]: I can't see how. Can you please expand your idea?

Comment (MaximKudriavtsev) [reply packages/dx-grid-core/src/plugins/table-band-header/computeds.ts]: My bed, you are right

File: packages/dx-grid-core/src/plugins/table-band-header/computeds.ts [hunk 2]
```diff
@@ -73,3 +75,67 @@ export const tableHeaderColumnChainsWithBands: GetHeaderColumnChainsFn<
 
   return [...bandChains, ...chains.slice(maxBandRowIndex)];
 };
+
+const getBandLevel: PureComputed<[any[], string, number?], number> = (
+  bands, bandTitle, level = 0,
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-band-header/computeds.ts]: Should we use the type `ColumnBands` instead of `any[]`.

File: packages/dx-grid-core/src/plugins/table-band-header/computeds.test.ts [hunk 3]
```diff
@@ -140,4 +143,103 @@ describe('TableBandHeader Plugin computeds', () => {
       );
     });
   });
+
+  describe('#columnBandLevels', () => {
+    it('should in simple case', () => {
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-band-header/computeds.test.ts]: "Should work..." ?
