### PR TITLE
fix(react-grid): check next column name by column.name instead type

### LINKED ISSUE #2397: Wrong render of cell`s separators for resizing
When the TableColumnResizing has `nextColumn` resizingMode, the grid may render a separator to resize the column which isn't allowed to be resized. An attempt to resize that column crashes the project.

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2397

### CODE REVIEW

**Comment by LazyLahtak** [comment]
FPR

File: packages/dx-react-grid/src/plugins/table-header-row.tsx [hunk 1]
```diff
@@ -8,7 +8,6 @@ import {
   tableRowsWithHeading,
   isHeadingTableCell,
   isHeadingTableRow,
-  getLastColumnName,
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid/src/plugins/table-header-row.tsx]: We should also remove this function from tests. (mock and import)

File: packages/dx-react-grid/src/plugins/table-header-row.tsx [hunk 2]
```diff
@@ -94,7 +92,7 @@ class TableHeaderRowBase extends React.PureComponent<TableHeaderRowProps> {
                     draggingEnabled={draggingEnabled && atLeastOneDataColumn}
                     resizingEnabled={
                       tableColumnResizingEnabled
-                      && (!lastColumn || columnResizingMode === 'widget')
+                      && (!!nextColumnName || columnResizingMode === 'widget')
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid/src/plugins/table-header-row.tsx]: Note: very wired using `widget` as a sting in a lot of places instead of using one constant.

**Comment by LazyLahtak** [comment]
FPR
