### PR TITLE
fix(react-scheduler): make it possible to drag-drop appointments in MonthView with AllDayPanel plugin

### LINKED ISSUE #2274: Impossible to drag-drop appointments in MonthView with AllDayPanel
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Scheduler

### Current Behaviour
Impossible to drag-drop appointments in MonthView with AllDayPanel

### Expected Behaviour
It should be possible to drag-drop appointments in MonthView with AllDayPanel

### Environment

- devextreme-reactive: 2.0.3
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #2274

### CODE REVIEW

File: packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx [hunk 1]
```diff
@@ -138,9 +138,12 @@ class DragDropProviderBase extends React.PureComponent<
     }
 
     const tableCellElementsMeta = timeTableElementsMeta;
-    const allDayCellsElementsMeta = allDayElementsMeta
-      || { getCellRects: [] }; // not always AllDayPanel exists
 
+    // AllDayPanel doesn't always exist
+    let allDayCellsElementsMeta = allDayElementsMeta;
+    if (!allDayElementsMeta || !allDayElementsMeta.getCellRects) {
+      allDayCellsElementsMeta = { getCellRects: [] };
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx]: I think we should use a ternary operator here, to avoid to use `let` and simplify code.

**Comment by AryamnovEugeniy** [comment]
FPR

File: packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx [hunk 2]
```diff
@@ -140,10 +140,8 @@ class DragDropProviderBase extends React.PureComponent<
     const tableCellElementsMeta = timeTableElementsMeta;
 
     // AllDayPanel doesn't always exist
-    let allDayCellsElementsMeta = allDayElementsMeta;
-    if (!allDayElementsMeta || !allDayElementsMeta.getCellRects) {
-      allDayCellsElementsMeta = { getCellRects: [] };
-    }
+    const allDayCellsElementsMeta = !allDayElementsMeta || !allDayElementsMeta.getCellRects ?
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx]: The next syntax is better

```js
const allDayCellsElementsMeta = allDayElementsMeta && allDayElementsMeta.getCellRects
  ? allDayElementsMeta
  : { getCellRects: [] };
```

**Comment by AryamnovEugeniy** [comment]
FPR

File: packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx [hunk 3]
```diff
@@ -417,6 +417,39 @@ describe('DragDropProvider', () => {
       expect(defaultDeps.action.changeAppointment)
         .toBeCalledWith({ change: { startDate: new Date('2018-06-25 00:00'), endDate: new Date('2018-06-26 00:00'), allDay: undefined } }, expect.any(Object), expect.any(Object));
     });
+    it('should call cellIndex with array if allDayElementsMeta is an empty object', () => {
+      const getBoundingClientRect = jest.fn();
+      getBoundingClientRect.mockImplementationOnce(() => ({ height: 20, top: 20, bottom: 40 }));
```
Comment (ushkal) [inline packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx]: We do not re-define this mock so it's implementation can be inlined to getCellRects at line 427
