### PR TITLE
fix(react-grid): correct colspan calculating for group row when used with certain plugins

### LINKED ISSUE #3158: Summary row alignment issues with grouping and detail plugins.
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When introducing RowDetailState and TableRowDetail
Then TableSummaryRow will misalign columns. Assuming that your groupItems for SummaryState have these params showInGroupFooter: false, alignByColumn: true

### Expected Behaviour

Alignment by column parameter is respected

### Steps to Reproduce

Link to the example that reproduces the issue: [CodeSandbox](https://codesandbox.io/s/bold-mendel-tbjk6)

### Screenshots

image
image

### Environment

- devextreme-reactive: 2.7.2
- react: 16.13.1
- browser: Chrome 86.0.4240.111
- material-ui: 4.11.0

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #3158

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/table-group-row/helpers.ts [hunk 1]
```diff
@@ -86,3 +87,20 @@ export const calculateGroupCellIndent: PureComputed<[TableColumn, Grouping[], nu
 ) => (
   indentWidth * getGroupIndexByColumn(grouping, tableColumn)
 );
+
+export const sortAndSpliceColumns: PureComputed<[TableColumn[], number]> = (
+  tableColumns, firstVisibleColumn,
+) => {
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-group-row/helpers.ts:93]: `firstVisibleColumn` -> `firstVisibleColumnIndex` or something else... because it is a number type ?

File: packages/dx-grid-core/src/plugins/table-group-row/helpers.test.ts [hunk 2]
```diff
@@ -136,6 +138,69 @@ describe('TableRowDetail Plugin helpers', () => {
...
+        ))
+          .toEqual([groupColumn, otherColumn, dataColumn]);
+
+        expect(sortAndSpliceColumns(
+          [otherColumn, otherColumn, groupColumn, otherColumn, dataColumn], 3,
+        ))
+          .toEqual([groupColumn, otherColumn, dataColumn]);
+      });
+
+      describe('two groups', () => {
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-group-row/helpers.test.ts:180]: should work with two groups

**Review by MaximKudriavtsev — APPROVED** [review]

**Review by AryamnovEugeniy — APPROVED** [review]
