### PR TITLE
fix(react-scheduler): make it possible to change allowDrag and allowResize in runtime

### LINKED ISSUE #2710: Scheduler - It is impossible to change allowDragging and allowResizing in runtime
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Steps to Reproduce
1) Open https://codesandbox.io/s/ancient-monad-rtpwp
2) Try dragging - it works
3) Disable dragging - dragging still works, though it shouldn't

Same with `allowResizing`

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #2710

### CODE REVIEW

File: packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx [hunk 1]
```diff
@@ -67,6 +72,27 @@ class DragDropProviderBase extends React.PureComponent<
...
+    }
+
+    return {
+      ...state,
+      appointmentContentTemplateKey:
+        isAllowDragUpdated ? state.appointmentContentTemplateKey : Math.random(),
+      appointmentTopTemplateKey:
+        isAllowResizeUpdated ? state.appointmentTopTemplateKey : Math.random(),
+      appointmentBottomTemplateKey:
+        isAllowResizeUpdated ? state.appointmentBottomTemplateKey : Math.random(),
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx]: Where do you set `allowDrag` and `allowResize` state properties?

File: packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx [hunk 2]
```diff
@@ -288,6 +288,70 @@ describe('DragDropProvider', () => {
       expect(allowResize)
         .toBeCalledWith(deps.template.appointmentTop.data);
     });
+    it('should change Resize render in runtime depending on allowResize prop', () => {
+      const allowResizing = () => true;
+      const deps = {
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx]: Does it necessary for the test?

Comment (AryamnovEugeniy) [reply packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx]: Yes. We need these templates, otherwise they wouldn't exist and Resize component wouldn't be rendered at all
