### PR TITLE
fix(react-scheduler): display horizontal appointments in chronological order

### LINKED ISSUE #2570: Scheduler - Appointments are placed in non-chronological order
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

In all of the demos with a month view, each day displays appointments in reverse chronological order.
For example, June 28th of the Art School demo shows these events:

1. Meeting of Instructors 12:00 PM - 12:30 PM
2. Monthly Planning 9:30 AM - 11:30 AM

### Expected Behaviour

The appointments should be placed in chronological order, e.g.
1. Monthly Planning 9:30 AM - 11:30 AM
2. Meeting of Instructors 12:00 PM - 12:30 PM

### Steps to Reproduce

You can reproduce this issue using the [Art School Demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/overview/)

### Screenshots

https://i.imgur.com/kLgPNqv.png

### Environment

- devextreme-reactive: 2.3.0
- react: 16.12.0
- browser: Google Chrome

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #2570

### CODE REVIEW

File: packages/dx-scheduler-core/src/utils.ts [hunk 1]
```diff
@@ -81,13 +81,20 @@ export const viewPredicate: ViewPredicateFn = (
...
+      if (a.allDay && !b.allDay) return -1;
+      if (!a.allDay && b.allDay) return 1;
+      if (a.allDay && b.allDay) {
+        if (a.end.isBefore(b.end)) return 1;
+        if (a.end.isAfter(b.end)) return -1;
+      }
+    }
+    if (a.start.isBefore(b.start)) return -1;
+    if (a.start.isAfter(b.start)) return 1;
+    if (a.start.isSame(b.start)) {
```
Comment (MaximKudriavtsev) [inline packages/dx-scheduler-core/src/utils.ts]: if ...

**Comment by AryamnovEugeniy** [comment]
FPR
