### PR TITLE
fix(react-grid-material-ui): apply page size selector position only for Edge

### LINKED ISSUE #2788: Grid page size Select scrolls to top on open
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When I click on the `Select` component in order to change the page size in the Grid, the page scrolls to top (Material-UI implementation)

Seems to be related with the `position: absolute` added in this line: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx#L31

### Expected Behaviour

The scroll should not be affected when I open the page size `Select`

### Steps to Reproduce

Just click to the page size `Select`, make sure you scrolled down first in order to open the page size select (so you can see the scroll jump)

Link to the example that reproduces the issue: [https://codesandbox.io/s/qw73m](https://codesandbox.io/s/qw73m) / [https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/) (every grid with pagination)

### Screenshots

Screen Shot 2020-03-31 at 5 11 00 PM

### Environment

- devextreme-reactive: 2.5.1
- react: 16.8.3
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.5

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2788

### CODE REVIEW

File: packages/dx-react-grid-material-ui/src/templates/constants.js [hunk 1]
```diff
@@ -0,0 +1 @@
+export const IS_EDGE_MEDIA_QUERY = '@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none)';
```
Comment (AryamnovEugeniy) [inline packages/dx-react-grid-material-ui/src/templates/constants.js:1]: I suggest IS_OLD_EDGE_MEDIA_QUERY

File: packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx [hunk 2]
```diff
@@ -28,7 +29,10 @@ const styles = theme => ({
     top: 2,
   },
   selectMenu: {
-    position: 'absolute !important',
+    // NOTE: fix position for non-chromium Edge
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx:32]: Can we add a ticket number (numbers) here?
