### PR TITLE
fix(react-grid): normalize scroll position in Edge browser

### LINKED ISSUE #1557: React Grid: Virtual scrolling not working (Edge)
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart

### Current Behaviour

Draws blank grid.

### Steps to Reproduce (for Bugs)

[Virtual scrolling demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/)

- Open in Edge
- Scroll all the way to the right
- Scroll down

-> The grid is blank.

- Scroll left and the rows appear again.

### Environment
- browser: Edge
- bootstrap: 3 & 4
- material-ui: Light and Dark theme

P.S.: Do you prefer that we report issues here on Github or the DevExpress support tickets?

### PR DESCRIPTION
**Pull request by ushkal**
fixes #1557

### CODE REVIEW

File: packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx [hunk 1]
```diff
@@ -34,6 +35,8 @@ export class VirtualTableLayout extends React.PureComponent {
     this.getRowHeight = this.getRowHeight.bind(this);
     this.updateViewport = this.updateViewport.bind(this);
     this.handleContainerSizeChange = this.handleContainerSizeChange.bind(this);
+
+    this.isEdgeBrowser = isEdgeBrowser();
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx]: On the server `this.isEdgeBrowser = false` because if customer use server-side rendering window is `undefined`

And when user will open a page by Edge browser `this.isEdgeBrowser = false`.

NOTE: I can mistake 😢
