### PR TITLE
fix(react-grid-demos): add margin for custom numeric input

### LINKED ISSUE #2520: Numeric input has no margin in Demo
The Customize Filter Row Appearance demo's custom numeric input has no margin in Material-UI.

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2520

### CODE REVIEW

File: packages/dx-react-grid-demos/src/demo-sources/grid-filtering/material-ui/advanced-filter-row.jsx [hunk 1]
```diff
@@ -16,12 +16,13 @@ const FilterIcon = ({ type, ...restProps }) => {
   return <TableFilterRow.Icon type={type} {...restProps} />;
 };
 
-const styles = {
+const styles = theme => ({
   numericInput: {
+    marginRight: theme.spacing(1),
```
Comment (ushkal) [inline packages/dx-react-grid-demos/src/demo-sources/grid-filtering/material-ui/advanced-filter-row.jsx]: should be 
```
styles = ...
  root: {
    margin: theme.spacing(1),
  },
...
classes={{
  input: numericInput,
  root: classes.root,
```
