### PR TITLE
fix(react-grid): split band columns with the same name but different parents

### LINKED ISSUE #2617: Band column cant divided correctly in some situation
image

Hi, i got a problem in this picture, you can see the middle line cell melt to one, but they have different father. They are expected to be two cell ! How could i accomplish this feature. any advice would be helpful !

### PR DESCRIPTION
**Pull request by ushkal**
fixes #2617

### CODE REVIEW

**Comment by ushkal** [comment]
FPR

File: packages/dx-grid-core/src/plugins/table-band-header/helpers.ts [hunk 1]
```diff
@@ -16,24 +16,27 @@ export const isBandedOrHeaderRow: IsSpecificRowFn = tableRow => isBandedTableRow
...
+  columnName, bands, tableRowLevel, key = '',
   level = 0, title = null, result = null,
 ) => bands.reduce((acc, column) => {
   if (column.columnName === columnName) {
-    return { ...acc, title, level };
+    return { ...acc, title, level, key };
   }
   if (column.children !== undefined) {
+    const bandTitle = level > tableRowLevel ? title : column.title;
+    const bandKey = level > tableRowLevel ? key : `${key}_${bandTitle}`;
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/table-band-header/helpers.ts]: Should we extract `level > tableRowLevel` into one more variable?

Comment (ushkal) [reply packages/dx-grid-core/src/plugins/table-band-header/helpers.ts]: Yep, good point
