### PR TITLE
fix(react-scheduler): fix create an appointment on the first call of AppointmentForm

### LINKED ISSUE #2271: Appointment cannot be created in the first form though it can be created in the following forms
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Scheduler

### Current Behaviour
Appointment cannot be created in the first form that was called in Editing mode in Scheduler.

### Expected Behaviour
Appointment should be created

### Steps to Reproduce
1) Call AppointmentForm.
2) Save a new Appointment.
3) Appointment hasn't been saved.

### Screenshots
Appointment is not created

### Environment

- devextreme-reactive: 2.0.3

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #2271

### CODE REVIEW

File: packages/dx-react-scheduler/src/plugins/editing-state.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ class EditingStateBase extends React.PureComponent<EditingStateProps, EditingSta
   commitDeletedAppointment: ActionFn<any>;
 
   static defaultProps: Partial<EditingStateProps> = {
-    defaultEditingAppointment: {},
+    defaultEditingAppointment: undefined,
     defaultAppointmentChanges: {},
     defaultAddedAppointment: {},
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/editing-state.tsx]: Should we apply this change to other fields?

Comment (AryamnovEugeniy) [reply packages/dx-react-scheduler/src/plugins/editing-state.tsx]: No< we shouldn't. These should be empty objects in order to be able to edit correctly.
