### PR TITLE
fix(chart-core): add handler only when window exists

### LINKED ISSUE #3083: Build error using EventTracker when running Gatsby Build
### I'm using ...

- [ ] React Grid
- [X] React Chart
- [ ] React Scheduler

### Current Behaviour
Using the component EventTracking in the project, running Gatsby Build has a compilation error (see screenshot below):
**"window" is not available during server side rendering**

### Expected Behaviour
Build should complete successfully.

### Steps to Reproduce
1. Create a new Gatsby project.
2. Copy paste any example code from tooltip component:
https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/tooltip/
3. Run Gatsby Build command line.

### Screenshots

image

### Environment
- devextreme-reactive: 2.7.1
- gatsby: 2.21.1
- react: 16.13.1
- browser: Chrome 85.0.4183.102 (64bits)
- bootstrap: none
- react-bootstrap: none
- material-ui/core: 4.9.12

### Suggestion Solution
Replace faulty code by
```
    if (typeof window !== 'undefined' && window) {
      if ('ontouchstart' in window) {
        handlers.touchstart = moveHandler;
      } else {
        handlers.mousemove = moveHandler;
        handlers.mouseleave = leaveHandler;
      }
    }
```

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #3083
(Based on #3084)

### CODE REVIEW

**Review by AryamnovEugeniy — APPROVED** [review]

File: packages/dx-chart-core/src/utils/event-tracker.ts [hunk 1]
```diff
@@ -60,17 +61,19 @@ export const buildEventHandlers = (
...
+    }
+    if (pointerMoveHandlers.length) {
+      const moveHandler = buildEventHandler(seriesList, pointerMoveHandlers);
+      const leaveHandler = buildLeaveEventHandler(pointerMoveHandlers);
+      if ('ontouchstart' in window) {
+        handlers.touchstart = moveHandler;
+      } else {
+        handlers.mousemove = moveHandler;
+        handlers.mouseleave = leaveHandler;
+      }
```
Comment (MaximKudriavtsev) [inline packages/dx-chart-core/src/utils/event-tracker.ts:76]: A simple structure better than a nested hierarchy

```js
if (!hasWindow) return handlers;
if (clickHandlers.length) {
...
```

**Comment by mstephano** [comment]
WOW this is a great fix with test units! I really appreciate it, thank you very much!!
