### PR TITLE
fix(react-grid): fix hidden tall rows in VirtualTable

### LINKED ISSUE #745: Row detail with height greater than Virtual Table height breaks row layout
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
When a row detail's height is greater than the Virtual Table's height, scrolling in the detail breaks the <tr> layout. See GIF:
feb-14-2018 09-56-21

### Expected Behaviour
Row detail should be allowed arbitrary height and scrolling should be smooth

### Steps to Reproduce (for Bugs)

Create a Virtual Table with any specified height and create a row with row detail with height greater than specified height. Scroll in row detail.

devextreme-reactive: xxx
react: 1.0.0-rc.1
browser: Chroms latest release
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.30

### PR DESCRIPTION
**Pull request by kvet**
fixes #745

### CODE REVIEW

File: packages/dx-react-grid/src/components/table-layout/virtual-table-utils.js [hunk 1]
```diff
@@ -14,21 +14,25 @@ export const getVisibleRows = (rows, viewportTop, viewportHeight, getRowHeight)
...
+    const lastIndex = result.length - 1;
+    const last = result[lastIndex];
 
     const height = getRowHeight(row);
     const nextPosition = position + height;
     if (
-      (viewportTop <= position && position < bottom
-        && viewportTop < nextPosition && nextPosition <= bottom) ||
-      (viewportTop > position && nextPosition > bottom)
+      (position >= viewportTop && position < bottom) ||
```
Comment (SergeyAlexeev) [inline packages/dx-react-grid/src/components/table-layout/virtual-table-utils.js]: Can we rename `bottom` to `viewportBottom`? It makes this condition more readable.
