### PR TITLE
fix(react-chart): animate series after axes finished rerendering

### LINKED ISSUE #2823: Bug appears when applying data to bar charts
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x ] React Chart
- [ ] React Scheduler

### Current Behaviour

I obtained an array containing some data from some wb API and found out that the bar chart would not display the information given correctly.
When I deleted the ArgumentAxis and the ValueAxis it worked.

### Expected Behaviour

The bar chart was supposed to display information correctly

### Steps to Reproduce

I dont know
Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

image

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #2823

### CODE REVIEW

File: packages/dx-chart-core/src/plugins/controller-component/computeds.ts [hunk 1]
```diff
@@ -17,5 +20,10 @@ export const getReadiness = ({ pane, ...restLayouts }, { current }) => {
...
   });
   return Math.abs(bbox.width - width) < DIFFERENCE &&
-  Math.abs(bbox.height - height) < DIFFERENCE;
+    Math.abs(bbox.height - height) < DIFFERENCE
+    && checkPreviousDataAndAxes(isPreviousDataEmpty, axesExist);
 };
+
+const checkPreviousDataAndAxes = (
+  isPreviousDataEmpty: boolean, axesExist: boolean,
+) => (!isPreviousDataEmpty && axesExist) || !axesExist;
```
Comment (MaximKudriavtsev) [inline packages/dx-chart-core/src/plugins/controller-component/computeds.ts:29]:
```ts
const isPreviousDataEmptyOrNoAxes = (
  isPreviousDataEmpty: boolean, axesExist: boolean,
) => !isPreviousDataEmpty || !axesExist;
```

File: packages/dx-chart-core/src/plugins/controller-component/computeds.ts [hunk 2]
```diff
@@ -1,7 +1,10 @@
 import { DIFFERENCE } from '../../constants';
 
 /** @internal */
-export const getReadiness = ({ pane, ...restLayouts }, { current }) => {
+export const getReadiness = (
```
Comment (ushkal) [inline packages/dx-chart-core/src/plugins/controller-component/computeds.ts:4]: Side note: maybe rename this function to `isReady`?

File: packages/dx-react-chart/src/plugins/axis.tsx [hunk 3]
```diff
@@ -219,6 +220,7 @@ class RawAxis extends React.PureComponent<RawAxisProps> {
     // Only one of templates is rendered then, the other is discarded.
     return (
       <Plugin name="Axis">
+        <Getter name="axesExist" value={true} />
```
Comment (ushkal) [inline packages/dx-react-chart/src/plugins/axis.tsx:223]: It's sufficient to specify just `<Getter name="axesExist" value />` as we do for other boolean getters
