### PR TITLE
fix(react-grid): correct calculation of available row count in infninite scrolling mode

### LINKED ISSUE #2197: An empty space appears after the end of the table on infinite scrolling
When you reach the end of the table on infinite scrolling, an empty space appears. This looks like new rows are loading. The size of the space equals the pageSize property of the VirtualTableState plugin.

image
image

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fix #2197

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts [hunk 1]
```diff
@@ -101,8 +101,12 @@ export const trimRowsToInterval: PureComputed<[VirtualRows, Interval]> = (
...
 export const getAvailableRowCount: PureComputed<[boolean, number, number, number], number> = (
   infiniteScroll, newCount, lastCount, totalRowCount,
-) => (
-  infiniteScroll
-    ? Math.max(newCount, lastCount)
+) => {
+  const maxWhenInfiniteScrolling = Math.min(
+    Math.max(newCount, lastCount),
+    totalRowCount);
+  return (infiniteScroll
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: If `infiniteScroll` is a boolean variable, I suggest using the next variable name - `isInfiniteScrolling`

Comment (MaximKudriavtsev) [reply packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: You have 3 variables - `newCount`, `lastCount`, `totalRowCount`. You should add the `Row` word into each name or remove this word from `totalRowCount`

Comment (MaximKudriavtsev) [reply packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: You calculate `maxWhenInfiniteScrolling` variable always but use it only `infiniteScroll` is `true`

File: packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx [hunk 2]
```diff
@@ -75,9 +75,12 @@ class VirtualTableStateBase extends React.PureComponent<VirtualTableStateProps,
       getRows(newPageIndex, loadCount);
 
       const virtualRowsCache = trimRowsToInterval(virtualRows, newBounds);
-      const newRowCount = infiniteScrolling
-        ? Math.max(newBounds.end + loadCount, stateAvailableCount)
-        : totalRowCount;
+      const newRowCount = getAvailableRowCount(
+        infiniteScrolling,
```
Comment (MaximKudriavtsev) [inline packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: `infiniteScrolling` -> `isInfiniteScrolling` ?

Comment (MaximKudriavtsev) [reply packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: newRowCount -> nextRowCount ?
But we should use only one word for variables. `next` / `new`

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts (hunk 1 above)
Comment (MaximKudriavtsev) [reply packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: We should add tests for new functionality

File: packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx (hunk 2 above)
Comment (LazyLahtak) [reply packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: This `infiniteScrolling` comes from props. 
We can do: `{..., infiniteScrolling: isInfiniteScrolling, ... } = this.props`, but should we?

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts (hunk 1 above)
Comment (LazyLahtak) [reply packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: > You calculate `maxWhenInfiniteScrolling` variable always but use it only `infiniteScroll` is `true`

I can remove `maxWhenInfiniteScrolling` variable and calculate this in expression. But it may do code less readable. Should we do that?

File: packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx (hunk 2 above)
Comment (MaximKudriavtsev) [reply packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: @ushkal,

Maybe we should change the prop name too?

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts [hunk 3]
```diff
@@ -326,4 +326,35 @@ describe('VirtualTableState helpers', () => {
...
+        lastRowCount,
+        totalRowCount,
+      )).toEqual(totalRowCount);
+    });
+
+    it('should return max of nextRowCount or lastRowCount when infiniteScroll', () => {
+      const isInfniniteScroll = true;
+      const nextRowCount = 200;
+      const lastRowCount = 100;
+      const totalRowCount = 1000;
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts]: We can extract these variables to `describe` section to avoid copy paste

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts [hunk 4]
```diff
@@ -326,4 +326,35 @@ describe('VirtualTableState helpers', () => {
       });
     });
   });
+
+  describe('#getAvailableRowCount', () => {
+    it('should return totalCount when not infiniteScroll', () => {
```
Comment (MaximKudriavtsev) [inline packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts]: `should return totalCount when not infiniteScroll`
->
`should return totalCount when not infinite scrolling`

File: packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx (hunk 2 above)
Comment (MaximKudriavtsev) [reply packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: > We can do: {..., infiniteScrolling: isInfiniteScrolling, ... } = this.props, but should we?

I think we should

Comment (ushkal) [reply packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx]: prop name was coordinated with techwriters and I don't see why the current name is bad. Besides that, renaming prop is a bc

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts [hunk 5]
```diff
@@ -326,4 +326,33 @@ describe('VirtualTableState helpers', () => {
...
+
+    it('should return max of newRowCount or lastRowCount when infinite scrolling', () => {
+      const isInfniniteScroll = true;
+
+      expect(getAvailableRowCount(
+        isInfniniteScroll,
+        newRowCount,
+        lastRowCount,
+        totalRowCount,
+      )).toEqual(Math.max(newRowCount, lastRowCount));
```
Comment (ushkal) [inline packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts]: We should be split to 2 tests

**Comment by LazyLahtak** [comment]
FPR

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts (hunk 1 above)
Comment (ushkal) [reply packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts]: It will be more readable with implicit return

File: packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts [hunk 6]
```diff
@@ -327,6 +328,49 @@ describe('VirtualTableState helpers', () => {
...
+
+      expect(getAvailableRowCount(
+        isInfniniteScroll,
+        newRowCount,
+        lastRowCount,
+        totalRowCount,
+      )).toEqual(totalRowCount);
+    });
+
+    it('should return newRowCount if it more than lastRowCount in infinite scrolling', () => {
```
Comment (ushkal) [inline packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts]: Let's extract these 2 tests to a describe block named 'Infinite scrolling mode'
