### PR TITLE
fix(react-grid): fix colspan calculation

### LINKED ISSUE #3467: colspan wrongly set in group summaries cell,  which cause incorrect alignment
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The "Sale Amount" align incorrectly

### Expected Behaviour

The summaries cell align to right column

### Steps to Reproduce

1. Set `showColumnsWhenGrouped` on `TableGroupRow`
2. Drag the column to the grouping panel, and the column is placed after a summarized column (here,  "units" is summarized , so we drag the "customer" to the grouping panel )
3. Expand group  row

sandbox link:  https://codesandbox.io/s/infallible-almeida-zm6ky?file=/demo.js

### Screenshots

image

### Environment

- devextreme-reactive: 2.7.6

### Description

Seems `tableGroupCellColSpanGetter` wrongly calculate,  because there are  2 `groupSummaryChain` started with 'custom' columnName,  one is for group type column,  another is for data type column.  But `chain` final set to `undefined` by `dataColumnGroupedBy` condition

### PR DESCRIPTION
**Pull request by Krijovnick**
Fixes #3467, #3313

### CODE REVIEW

File: packages/dx-grid-core/src/plugins/table-group-row/computeds.ts [hunk 1]
```diff
@@ -114,12 +114,10 @@ export const tableGroupCellColSpanGetter: GroupCellColSpanGetter = (
 
   if (tableRow.type === TABLE_GROUP_TYPE) {
     const colName = tableColumn.column?.name;
-    const dataColumnGroupedBy =
-      tableRow.row.groupedBy === colName && tableColumn.type !== TABLE_GROUP_TYPE;
     const chains = groupSummaryChains(
       tableRow, tableColumns, groupSummaryItems, firstVisibleColumnIndex,
     );
-    const chain = chains.find(ch => !dataColumnGroupedBy && ch[0] === colName);
+    const chain = tableRow.row.groupedBy ? chains.find(ch => ch[0] === colName) : undefined;
```
Comment (torrac12) [inline packages/dx-grid-core/src/plugins/table-group-row/computeds.ts:120]: I have an question. 
when "tableRow.type === TABLE_GROUP_TYPE", if this mean "tableRow.row.groupedBy" always have an value?

I think we should only overwrite the colspan of `group type column`

Comment (torrac12) [reply packages/dx-grid-core/src/plugins/table-group-row/computeds.ts:120]: I think if there are multiple column type which have same column name,  we should get the colspan according to it's type.
Maybe we should use key of column in chains but not column name, to prevent there are mutiple chains start with same column name.

If a column is data type,  the colspan of it should not be the default value 1,  that will make the number of `td` less than we wanted,  because in some case render `null` instead `templatePlaceholder` in tableGroupRow plugin.

**Review by MikeVitik — APPROVED** [review]
