### PR TITLE
fix(react-grid-material-ui): correct disabled behaviour for inline cell editing

### LINKED ISSUE #2535: TableInlineCellEditing issues with EditingState columnExtensions editingEnabled: false
Hi, I've an issue when try to use TableInlineCellEditing in combination with <EditingState ... /> for disabling editing on some columns. 
When I click over cell where the editing was disabled, the cell become an editable control with the value correctly disabled. But when I click outside the che cell area, the cell remain in edit mode!

Moreover, from this moment if I click over other editable cell of others row I obtain this situation:

image

This is a portion of my code:

```
                    <EditingState
                        onCommitChanges={this.commitChanges}
                        //defaultEditingRowIds={[0]}
                        columnExtensions={[
                            { columnName: 'bill', editingEnabled: false },
                            { columnName: 'date', editingEnabled: false }
                        ]}
                    />
.....
                    <TableInlineCellEditing
                        selectTextOnEditStart={true}
                    />
```

### PR DESCRIPTION
**Pull request by LazyLahtak**
Fixes #2535

### CODE REVIEW

**Comment by LazyLahtak** [comment]
FPR

File: packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx [hunk 1]
```diff
@@ -48,14 +48,18 @@ const TableInlineCellEditingBase: React.SFC<TableInlineCellEditingProps> & {comp
...
-            {({}, { startEditCells }) => {
+            {({ isColumnEditingEnabled }, { startEditCells }) => {
               const { tableRow : { rowId }, tableColumn: { column } } = params;
               const { name: columnName } = column!;
 
               if (startEditAction !== 'click' && startEditAction !== 'doubleClick') {
                 throw new Error(INLINE_CELL_EDITING_ERROR);
               }
 
+              if (!isColumnEditingEnabled(columnName)) {
```
Comment (ushkal) [inline packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx]: Better invert this condition: 
```
if editingEnabled return editableCell
return ordinaryCell
```

**Comment by LazyLahtak** [comment]
FPR
