### PR TITLE
fix(react-scheduler): display time in Time Scale correctly when a DST change is present

### LINKED ISSUE #3104: Daylight change TimeCell bug in React Scheduler
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

When adding the plugin `WeekView` with a `startDayHour` prop to 1, navigating to 1 week before daylight change, let's say `25-31 October`, 
```javascript
<WeekView
   startDayHour={1}
   endDayHour={19}
/>
```
the timecell breaks, and will generate each time duplicates timecells.

### Expected Behaviour

It should start at `00:00` instead of creating duplicates timecells or allow activating/deactivating daylightChange behavior.

### Steps to Reproduce

[Codesandbox demo link](https://codesandbox.io/s/confident-hertz-in44j?file=/demo.js)

1. Navigate to `25-31 October`. What really matters is it should be before daylight change `1st Nov`
2. Navigate using date navigator arrow to next week `1-7 Nov`

### Screenshots

CZFcti62HQ

### Environment

- devextreme-reactive: 2.7.1
- react: ^16.13.1
- browser: Google Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: ^4.11.0

### PR DESCRIPTION
**Pull request by AryamnovEugeniy**
Fixes #3104

### CODE REVIEW

**Review by LazyLahtak — APPROVED** [review]

File: packages/dx-react-scheduler/src/plugins/day-view.tsx [hunk 1]
```diff
@@ -108,22 +125,28 @@ class DayViewBase extends React.PureComponent<VerticalViewProps> {
           }}
         />
 
+        <Getter
+          name="timeCellsData"
+          computed={this.timeCellsDataComputed(viewName, startDayHour, endDayHour)}
+        />
+
```
Comment (MaximKudriavtsev) [inline packages/dx-react-scheduler/src/plugins/day-view.tsx:132]: Can we move this getter in BasicView? I know it needs only in Week and Day. Maybe conditional getter rendering or conditional getter computing will be helpful

**Review by MaximKudriavtsev — APPROVED** [review]
